# Conexões
max_connections = 100

# Memória
shared_buffers = 1024MB
work_mem       = 16MB

# Log
log_statement              = 'none'
log_min_duration_statement = 1000
log_timezone               = 'UTC'

# Localização
timezone = 'UTC'
